package lib::JunkGenerator;

use strict;
use warnings;

# =========================================================================
#  SOFTWARE   : Obfuscator by Mr.Rm19
#  AUTHOR     : Mr.Rm19
#  GITHUB     : github.com/Rm19x
#  LICENSE    : Open Source - Copyright (c) 2026 Mr.Rm19
# =========================================================================

our $VERSION = '1.0';

# Fungsi utama untuk menyisipkan junk code ke dalam blok PHP
sub inject {
    my ($class, $php_code) = @_;

    $php_code = $class->_obfuscate_numbers($php_code);

    $php_code = $class->_inject_dead_functions($php_code);

    return $php_code;
}

sub _obfuscate_numbers {
    my ($self, $code) = @_;

    $code =~ s/\b(\d+)\b/
        my $num = $1;
        my $choice = int(rand(3)); # Pilih secara acak metode pengacakan

        if ($choice == 0) {
            # Metode No. 23: Operasi Matematika Rumit
            my $rand_factor = int(rand(50)) + 1;
            my $multiplier  = $num * $rand_factor;
            "(( $multiplier / $rand_factor ) + " . (int(rand(10)) * 0) . ")";
        }
        elsif ($choice == 1) {
           
            sprintf("0x%X", $num);
        }
        else {
           
            sprintf("0b%b", $num);
        }
    /gex;

    return $code;
}

sub _inject_dead_functions {
    my ($self, $code) = @_;

    my $junk_prefix = "_mr_rm19_junk_" . int(rand(1000));
    
    my $dead_code = "\n// --- Junk Section Generated by Mr.Rm19 ---\n";
    
    for (my $i = 1; $i <= 3; $i++) {
        my $val1 = int(rand(100)) + 1;
        my $val2 = int(rand(50)) + 1;
        
        $dead_code .= "function ${junk_prefix}_func$i(\$param1 = $val1, \$param2 = $val2) {\n";
        $dead_code .= "    \$calc_a = sin(\$param1) * cos(\$param2);\n";
        $dead_code .= "    \$calc_b = log(\$calc_a ? abs(\$calc_a) : 1) + sqrt($val1);\n";
        $dead_code .= "    if (\$calc_b < 0) { return floatval(\$calc_b); }\n";
        $dead_code .= "    return (\$calc_a ^ \$val2);\n";
        $dead_code .= "}\n";
    }
    
    $code .= $dead_code;

    return $code;
}

1;